### ISSUE TITLE
可以在打包前删除文件和文件夹名字后面的 MD5 吗？

### ISSUE THREAD

**Issue by tanst** [LoneKingCode/notion-backup#1]
这个地方的 [MD5](https://github.com/LoneKingCode/notion-backup#7-%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)，可以在打包成 zip 之前删除吗？

**Comment by LoneKingCode** [comment]
那一串相当于id，是唯一标识，如果子页面同名的话，文档内引用地址就出问题了，虽然看着好长
比如导出html时，如果去掉ID，那页面内引用多个同名./xxxxx.html就有问题了，
不过去掉就整齐好多，同名也能少出现，考虑加个额外选项可选是否去掉MD5

**Comment by LoneKingCode** [comment]
[支持去除所有文件和文件夹的id，并重新生成压缩包](https://github.com/LoneKingCode/notion-backup/commit/32e040fefe344b9425e27c3a3f77b50c3e413b46)
修改全局变量REMOVE_FILES_ID即可
