### ISSUE TITLE
一直403不知道是什么原因

### ISSUE THREAD

**Issue by lancer-wang** [LoneKingCode/notion-backup#2]
403 Client Error: Forbidden for url: https://www.notion.so/api/v3/loginWithEmail

**Comment by LoneKingCode** [comment]
1.notion api域名套了cloudflare的cdn，国外有些IP有可能会弹出cf的验证，就会出错，你是哪里的机器测试的
2.用户名和密码配置好了吗，或者用token代替

**Comment by lancer-wang** [comment]
> 1.notion api域名套了cloudflare的cdn，国外有些IP有可能会弹出cf的验证，就会出错，你是哪里的机器测试的 2.用户名和密码配置好了吗，或者用token代替

大阪的机器，之前一直可以，最近突然不行了，我去其他的机器试试

**Comment by LoneKingCode** [comment]
其实你最简单curl https://www.notion.so/api/v3/loginWithEmail 看看返回的是不是带cloudflare的一些信息就知道了
比如有 <noscript id="cf-captcha-bookmark" class="cf-captcha-info">

**Comment by lancer-wang** [comment]
> 

确实是遇到cf验证了。。

**Comment by LoneKingCode** [comment]
> 请问这个该如何解决呢？

无解 要换IP的·
