### ISSUE TITLE
是需要两个仓库吗

### ISSUE THREAD

**Issue by xming521** [LoneKingCode/notion-backup#3]
还需要再新建一个私有仓库存备份内容吗，好像github actions 不配置的话找不到自己的私有仓库

**Comment by LoneKingCode** [comment]
直接创建个私有仓库把本项目的文件都提交进去，
.workflow/backup.yml中的
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
去掉注释就可以测试下，push会触发下ci执行
改下环境变量NOTION_TOKEN

**Comment by LoneKingCode** [comment]
一个仓库就可，github actions 执行时的仓库就是.github/workflows/backup.yml所在的仓库
CI执行完，这个仓库就会多一个目录"backup"

**Comment by xming521** [comment]
![image](https://user-images.githubusercontent.com/32786500/223036170-37ffa5ab-7c8b-4916-8444-c40afbb570be.png)
不行 仓库什么变化都没有

**Comment by LoneKingCode** [comment]
![image](https://user-images.githubusercontent.com/11244921/223048013-86c0fa9c-c064-4a7b-82e4-0978480b38f1.png)
你设置备份配置了没有

**Comment by LoneKingCode** [comment]
配置为空，应该是备份所有空间，
我等会看看下代码是不是有问题

**Comment by xming521** [comment]
我就是备份的所有空间，那个链接能拿到所有的文件都是正确的，可能push代码出问题了？

**Comment by LoneKingCode** [comment]
链接对了，应该是下载文件&解压的步骤错了，更新下notion_backup.py
看看下输出是什么
    if os.path.exists(savePath):  
        print('保存文件:' + savePath)
    else:
        print('保存文件:' + savePath +'失败')

**Comment by xming521** [comment]
![image](https://user-images.githubusercontent.com/32786500/223064448-fe6a7883-8219-467f-8038-2acf3261fff0.png)
我遍历了一下文件都在

**Comment by LoneKingCode** [comment]
发现问题了，.gitignore里去掉backup/ 
我之前本地调试加的忘记去掉了
