### ISSUE TITLE
notion昨天改规则了，需要多解压一次

### ISSUE THREAD

**Issue by lancer-wang** [LoneKingCode/notion-backup#4]
savepath2 = savePath.replace(".zip","")
    for file in os.listdir(savepath2):
        file_path = os.path.join(savepath2, file) 
        unzip(file_path)
        os.remove(file_path)
稍微改了下

**Comment by LoneKingCode** [comment]
谢谢提醒
不过我刚看了下，
![image](https://user-images.githubusercontent.com/11244921/225270994-94e52fea-db32-4946-a233-bf3e14bece20.png)
我用接口还有网页内导出的还是没有内嵌压缩包的

**Comment by LoneKingCode** [comment]
你是导出页面，还是工作空间发现的有内嵌压缩包？

**Comment by lancer-wang** [comment]
> 你是导出页面，还是工作空间发现的有内嵌压缩包？
![image](https://user-images.githubusercontent.com/69783837/225272883-1ed27c81-6b7d-4dd2-8e6f-efa38e017dcb.png)

就本来只有上面那个压缩包
然后解压后是这样
![image](https://user-images.githubusercontent.com/69783837/225273014-574af943-3f24-4f78-9293-7cc8fa9991a1.png)
昨天开始我的里面变成了一个压缩包

这个是我解压后的，本来是个压缩包
![image](https://user-images.githubusercontent.com/69783837/225273145-2b6bd76f-5fea-48cb-ace0-e5c153472778.png)

**Comment by LoneKingCode** [comment]
已修改，导出整个workspace的话会有内嵌压缩包
```python
    zip_dir = savePath.replace(".zip", "")
    for file in os.listdir(zip_dir):
        file_path = os.path.join(zip_dir, file)
        if '.zip' in file_path:
            unzip(file_path)
            os.remove(file_path)
```
