### ISSUE TITLE
backup/****'s Notion.zip unzip fail,File is not a zip file

### ISSUE THREAD

**Issue by xming521** [LoneKingCode/notion-backup#5]
下载到电脑上能解压 用代码不能解压
![image](https://user-images.githubusercontent.com/32786500/229029716-c62c4438-4041-484d-874c-fcaaadf9b987.png)

**Comment by xming521** [comment]
自己电脑上下载下来是正常的zip，服务器下载下来是个需要登陆的网页

**Comment by LoneKingCode** [comment]
发现问题了，可能下载aws的s3文件时也需要授权之类的了
我看看

**Comment by LoneKingCode** [comment]
已修复 测试通过了
主要是增加了个file_token的获取
